# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vgiordan <vgiordan@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/17 11:24:17 by vgiordan          #+#    #+#              #
#    Updated: 2022/09/20 20:35:05 by vgiordan         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = $(addprefix srcs/str/ft_, strlen.c strchr.c strdup.c striteri.c strjoin.c strlcat.c strlcpy.c strmapi.c strncmp.c strnstr.c strrchr.c strtrim.c substr.c)

OBJS = ${SRCS:.c=.o}

NAME = MAXXXXXXXXX

RM = rm

CC = gcc

INCLUDES = includes

CFLAGS = -Wall -Wextra -Werror

.c.o:
			${CC} ${CFLAGS} -I ${INCLUDES} -c $< -o ${<:.c=.o}

${NAME}:	${OBJS}

all:		${NAME} 

clean:
		-rm ${OBJS}

fclean:	clean
			${RM} ${NAME}

re:		fclean all

.PHONY: all clean fclean re DEL