# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vgiordan <vgiordan@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/09/17 11:24:17 by vgiordan          #+#    #+#              #
#    Updated: 2022/09/20 20:35:05 by vgiordan         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = ft_display_file.c

OBJS = ${SRCS:.c=.o}

NAME = ft_display_file

RM = rm -f

CC = gcc

CFLAGS = -Wall -Wextra -Werror

.c.o:
			${CC} ${CFLAGS} -c $< -o ${<:.c=.o}

${NAME}:	${OBJS}


all:		${NAME} 

clean:
			${RM} ${OBJS}

fclean:	clean
			${RM} ${NAME}

re:		fclean all

.PHONY: all clean fclean re